#
# Set up an action to monitor Contributor License Agreements (CLAs).
# See: https://github.com/marketplace/actions/cla-assistant-lite
#
# 1) Signature branch creation
# By default this action is configured to output *******
# The branch containing the signatures must not be protected.  To create an empty branch named "cla-signatures" to contain the siguatures run:
# git checkout --orphan cla-signatures
# git rm -rf .
# git commit --allow-empty -m "CLA signature branch creation"
#
# 2) PERSONAL_ACCESS_TOKEN
#
# A personal access token must be set up to allow this bot to commit.  To do this:
# a) Create a personal access token with repo scope
# b) Manually add the token to the repository's secrets as PERSONAL_ACCESS_TOKEN
#
# 3) allowlist
#
# If a GitHub username is included in the allowlist, they will not be required to sign the CLA.  This is useful for allowing bots to contribute without a CLA.

name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-document: 'https://github.com/chipkent/test-cla-signatures/blob/main/CLA.md'
          remote-organization-name: chipkent
          remote-repository-name:  test-cla-signatures
          branch: 'main'
          path-to-signatures: 'signatures/version1/cla.json'
          #allowlist: user1,bot*


